version: '3'

services:

  system_manager:  &system_manager
    build:
      context: .
    volumes:
      - '.:/usr/src/app'
    container_name: 'system_manager_api'
    ports:
      - 5000:5000
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - APP_SETTINGS=src.config.DevelopmentConfig
      - SECRET_KEY=PB3aGvTmCkzaLGRAxDc3aMayKTPTDd5usT8gw4pCmKOk5AlJjh12pTrnNgQyOHCH
      - MONGO_DATABASE=system_manager
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=rootpassword
      - MONGO_HOST=database
      - MONGO_PORT=27017
      - RABBITMQ_USER=rootuser
      - RABBITMQ_PASS=mypassverystrong
    depends_on:
      - database

  database:
    image: mongo:latest
    container_name: 'system_manager_mongo'
    environment:
      MONGO_INITDB_DATABASE: system_manager
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  rabbit:
    hostname: rabbit
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=rootuser
      - RABBITMQ_DEFAULT_PASS=mypassverystrong
    ports:
      - "15672:15672"
      - "5672:5672"

  consumer:
    <<: *system_manager
    container_name: 'system_manager_consumer'
    command: "./run_consumer.sh"
    ports:
      - 5001:5000
    depends_on:
      - rabbit
      - database
      - system_manager


volumes:
  mongodb_data_container: